version: "3"
services:
  mysql1:
    image: mysql:5.7
    networks:
      - wordpressnet1
    volumes:
      - mysqlvol1:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress1
      MYSQL_PASSWORD: wordpresspass123
  wordpress1:
    depends_on:
      - mysql1
    image: wordpress
    networks:
      - wordpressnet1
    volumes:
      - wordpressvol2:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql1
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wordpress1
      WORDPRESS_DB_PASSWORD: wordpresspass123
networks:
  wordpressnet1:
volumes:
  mysqlvol1:
  wordpressvol2:
